// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAjV2M0A5AHf4wLfRWmNqdixdUyj7btzE',
    appId: '1:362406352631:web:37ebd6909ed3a49b22e5f2',
    messagingSenderId: '362406352631',
    projectId: 'e-quickcount',
    authDomain: 'e-quickcount.firebaseapp.com',
    storageBucket: 'e-quickcount.appspot.com',
    measurementId: 'G-PW9V1P1E1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGE0u3OMwnO4qSWECQgT0nzD8C2NGbR0c',
    appId: '1:362406352631:android:7bbd7ca429a3201222e5f2',
    messagingSenderId: '362406352631',
    projectId: 'e-quickcount',
    storageBucket: 'e-quickcount.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMaf2C58TaKLZY_7x-a0xZcz5BiU5ls8M',
    appId: '1:362406352631:ios:b60ca0cebb9a707c22e5f2',
    messagingSenderId: '362406352631',
    projectId: 'e-quickcount',
    storageBucket: 'e-quickcount.appspot.com',
    iosBundleId: 'com.example.eQuickcount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMaf2C58TaKLZY_7x-a0xZcz5BiU5ls8M',
    appId: '1:362406352631:ios:affdbe774df7d4d022e5f2',
    messagingSenderId: '362406352631',
    projectId: 'e-quickcount',
    storageBucket: 'e-quickcount.appspot.com',
    iosBundleId: 'com.example.eQuickcount.RunnerTests',
  );
}
